import { prisma } from "./_env";
import { studentFile } from "../src/lib/studentFile";
import { signStudentDocument } from "../src/app/dashboard/students/[id]/dossier/actions";

async function runSmokeTests() {
  console.log("═════════════ SMOKE TEST — TROIS NATURES DE PIÈCES ═════════════\n");

  // 1. Test dossier de Jaya Ba (Dieynaba Ba)
  const jaya = await prisma.student.findUnique({
    where: { id: "b334c754-42be-4f31-abc8-7bfd88958858" },
    include: { school: true, enrollments: { include: { class: true } } },
  });

  if (!jaya) throw new Error("Jaya Ba introuvable");

  const adminActor = { userId: "admin-test", schoolId: jaya.schoolId, role: "ADMIN" as const };
  const jayaFile = await studentFile(adminActor, jaya.id);

  if (!jayaFile) throw new Error("Échec du chargement du dossier de Jaya Ba");

  console.log("1. DOSSIER DE JAYA BA (CE1) :");
  console.log(`- Total pièces applicables : ${jayaFile.lines.length}`);
  console.log(`- Pièces REQUISES applicables : ${jayaFile.completeness.required}`);
  console.log(`- Pièces acquises : ${jayaFile.completeness.received}`);
  console.log(`- Pièces validées : ${jayaFile.completeness.validated}`);
  console.log(`- Pièces manquantes : ${jayaFile.completeness.missing}`);
  console.log(`- TAUX DE COMPLÉTUDE : ${jayaFile.completeness.percent}%\n`);

  // Vérification de la complétude de Jaya Ba
  if (jayaFile.completeness.percent !== 50) {
    throw new Error(`Taux attendu 50%, obtenu ${jayaFile.completeness.percent}%`);
  }

  // Vérification des pièces AUTO
  const certif = jayaFile.lines.find((l) => l.label.toLowerCase().includes("certificat de scolarité"));
  console.log("2. PIÈCE AUTO (Certificat de scolarité) :");
  console.log(`- Nature : ${certif?.nature}`);
  console.log(`- Auto-généré : ${certif?.autoGenerated}`);
  console.log(`- Statut : ${certif?.status}`);
  console.log(`- Motif : ${certif?.autoReason}`);
  console.log(`- Lien direct : ${certif?.autoLink}`);
  if (!certif?.autoGenerated || certif.status !== "VALIDATED") {
    throw new Error("Le certificat de scolarité aurait dû être auto-généré et validé");
  }

  // Vérification du repli AUTO -> UPLOAD pour bulletin N-1
  const bulletin = jayaFile.lines.find((l) => l.label.toLowerCase().includes("bulletin"));
  console.log("\n3. REPLI AUTO -> UPLOAD (Bulletin N-1 nouvel arrivant) :");
  console.log(`- Nature : ${bulletin?.nature}`);
  console.log(`- Auto-généré : ${bulletin?.autoGenerated}`);
  console.log(`- Action effective : ${bulletin?.actionType}`);
  console.log(`- Message incitatif : ${bulletin?.actionPrompt}`);
  if (bulletin?.autoGenerated || bulletin?.actionType !== "UPLOAD") {
    throw new Error("Le bulletin N-1 sans historique aurait dû se replier en UPLOAD");
  }

  // Vérification des actions claires
  console.log("\n4. CLARTÉ DES ACTIONS (Poussent à agir) :");
  for (const l of jayaFile.lines) {
    console.log(`- [${l.actionType}] ${l.label} -> "${l.actionPrompt}" [${l.actionLabel}]`);
  }

  console.log("\n═════════════ TOUS LES SMOKE TESTS ONT RÉUSSI ═════════════");
}

runSmokeTests().catch((err) => {
  console.error("ÉCHEC DU SMOKE TEST :", err);
  process.exit(1);
});
